### ISSUE TITLE
Bug: while submitting topology via flux to Aapache Storm

### ISSUE THREAD

**Issue by msghasan** [DigitalPebble/storm-crawler#1045]
(https://github.com/DigitalPebble/storm-crawler/blob/d9ca991c514e5010805c5519971686eded4ab306/core/pom.xml#L25)
![Screenshot from 2023-02-28 15-06-08](https://user-images.githubusercontent.com/32441552/221815055-d4cd8dc2-7e09-4d4c-8ab7-38fbefbaf49a.png)

Apache storm uses snakeyaml 1.26 version and we are using 1.32 causing no such method exception.
https://github.com/apache/storm/blob/a432e99bca526886655cc1d5b2453a09b302b5ca/pom.xml#L305

I have not checked but all of a sudden topology was not getting submitted. I think through testing should be done before accepting PR.

Fix that I have used is belwo in side of dependency management
```
<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>commons-io</groupId>
				<artifactId>commons-io</artifactId>
				<version>2.11.0</version>
			</dependency>
			<dependency>
                <groupId>org.yaml</groupId>
                <artifactId>snakeyaml</artifactId>
                <version>${snakeyaml.version}</version>// this i have provided as 1.26
            </dependency>
		</dependencies>
	</dependencyManagement>
```

**Comment by jnioche** [comment]
> . I think through testing should be done before accepting PR.

I think thorough consideration should be given before lecturing people

**Comment by msghasan** [comment]
@jnioche Mark this as bug please

**Comment by rzo1** [comment]
The issue originates from the fact, that SC uses Maven range syntax to specifiy the version, see https://github.com/DigitalPebble/storm-crawler/blob/master/core/pom.xml#L25

This brings in snakeyaml 2.0, which removed the related constructor: https://github.com/snakeyaml/snakeyaml/commit/3e755d254aeaa902675053047fd53368a175565a#diff-a68d4fc960a9e7c7007e23eb2289cd82545302b6fd45f07bbdaba542a55df361

Consequently, as the dependency is not stable (due to range syntax) it brings in `2.0` and breaks applications. It really doesn't matter, that SC uses 1.32 and Storm 1.26 ;-)

**Comment by jnioche** [comment]
> I think through testing should be done before accepting PR.

thanks for reporting the issue but the comment above is rather unhelpful. PRs are tested and in this particular occurrence, it passed the tests fine at the time. If you have suggestions on how to improve the CI and test suite, your input will be appreciated

**Comment by msghasan** [comment]
@jnioche  Thanks for the quick fix all of a sudden without any code changes this error started happening.. And I am sorry if my concern sounded like a lecture.

I will make sure in future that I would be more careful while using my words.

> , which removed

thanks for the explanation.
