### ISSUE TITLE
Fix various quirks in OpenSearch archetype projet generation

### ISSUE THREAD

**Issue by rzo1** [DigitalPebble/storm-crawler#1153]
There are a few quirks in the generated archetype. 

For example, the mapping files do not correspond to the file names used in the index creation script. 

Moreover, the mappings aren't added to the project generated by the archetype, so you have to copy paste it from source or form within the JAR. Let's just ship them and make life of users easier.

**Comment by jnioche** [comment]
> For example, the mapping files do not correspond to the file names used in the index creation script.

the mapping files are named after the type of bolt that creates it. For status and metrics, the name of the component and the index is the same but this is not the case for indexer != content. Let's just change the init script so that it distinguishes them.

> Moreover, the mappings aren't added to the project generated by the archetype, so you have to copy paste it from source or form within the JAR. Let's just ship them and make life of users easier.

perhaps we should have them in the archetype only?
