### ISSUE TITLE
Does this crawler support javascript execution?

### ISSUE THREAD

**Issue by PatrickHuetter** [DigitalPebble/storm-crawler#142]
1) Does this crawler support javascript execution?
2) Does the crawler use selenium? (in this case it should be possible to use phantomJS or any other browser engine)

3) If it doesn't use selenium: Is it possible to integrate selenium easily? (I'm not very deep in the architecture yet, but i would investigate if it's possible)

4) Is it possible to trigger some hooks before extraction? For example: Click on a button before extracting elements, because the button triggers some ajax content load?

5) Is it possible to use a specific proxy for each crawling-job?

I'm asking regarding to my post on sf http://stackoverflow.com/questions/30887701/should-i-use-akka-io-apache-spark-mesos-or-storm-for-a-webcrawling-engine 

If some use-cases would be possible with this project, i would choose it as base and also contribute to it.

**Comment by jnioche** [comment]
Thanks for getting in touch Patrick

> 1) Does this crawler support javascript execution?

not yet

> 2) Does the crawler use selenium? (in this case it should be possible to use phantomJS or any other browser engine)

not yet but this is something we'd like to do. This would be done by implementing a custom protocol that would delegate the fetching to Selenuim.

> 3) If it doesn't use selenium: Is it possible to integrate selenium easily? (I'm not very deep in the architecture yet, but i would investigate if it's possible)

This has been done by some of users (@GuiForget  & @jakekdodd ) but as a custom ParseFilter IIRC. As I mentioned above this could also be done as a custom protocol implementation.

> 4) Is it possible to trigger some hooks before extraction? For example: Click on a button before extracting elements, because the button triggers some ajax content load?

Well, we have nothing at the moment so everything's possible. The way I see it, we'd be able to pass a navigation script as part of the configuration of the protocol in order to do what you described.

> 5) Is it possible to use a specific proxy for each crawling-job?

Not sure what you mean by crawling job. StormCrawler is not batch driven like for instance Apache Nutch, it runs continuously. Having said that you could have several topologies running at the same time but I am not sure why you'd do that.

Our [http protocol implementation can be configured to use a proxy](https://github.com/DigitalPebble/storm-crawler/blob/master/core/src/main/java/com/digitalpebble/storm/crawler/protocol/httpclient/HttpProtocol.java#L108) but that would be the same proxy used for the entire topology.

Do you mean https authentication?  Our protocol implementation does not handle that yet but it is definitely doable. Again, we could load the credentials via the configuration.

> If some use-cases would be possible with this project, i would choose it as base and also contribute to it.

That would be great. Apart from the things mentioned here, StormCrawler can already provide quite a few functionalities and you'd be able to leverage the core components (fetcher and parser bolts) without reinventing them.

**Comment by jnioche** [comment]
Have opened #144, let's discuss Selenuim there.

@PatrickHuetter please close this issue if you think I've answered all your questions

**Comment by koolma** [comment]
Hi @jnioche,
is it still true that stormcrawler is not able to work with JavaScript?

**Comment by jnioche** [comment]
Hi @koolma, see issue mentioned above (#144) in particular 
https://github.com/DigitalPebble/storm-crawler/issues/144#issuecomment-297671725
