### ISSUE TITLE
Enforce robots meta tags 

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#147]
See [http://www.google.com/support/enterprise/static/gsa/docs/admin/70/gsa_doc_set/admin_crawl/preparing.html#1076168]

`<meta name="robots" content="noarchive, nofollow"/>`

as well as  `rel="nofollow"` attribute  
`<a href="test1.html" rel="nofollow>no follow</a>`

**Comment by jnioche** [comment]
Nutch equivalent

[https://github.com/apache/nutch/blob/trunk/src/plugin/parse-html/src/java/org/apache/nutch/parse/html/HTMLMetaProcessor.java]

and 

[https://github.com/apache/nutch/blob/trunk/src/java/org/apache/nutch/parse/HTMLMetaTags.java]

**Comment by rkrombho** [comment]
I would really prefer if this behavior could be switched of and on with a configuration flip.
`rel=nofollow` should only be used for ranking links. Crawlers typically still follow those links but remove them from any sort of rank calculation.

Here is what the big search engine cralwers do with it:
https://en.wikipedia.org/wiki/Nofollow#Interpretation_by_the_individual_search_engines

Especially for whole web crawls it may still be important for crawlers to follow those links in order to find new pages irrespective of ranking those type of links.

**Comment by jnioche** [comment]
Thanks for your comments @rkrombho 

There seems to be different interpretations of what this is supposed to do indeed. The [doc for GSA](http://www.google.com/support/enterprise/static/gsa/docs/admin/70/gsa_doc_set/admin_crawl/preparing.html#1076168) which I mentioned previously implies that the links are not followed at all ("_The search appliance crawler retrieves and archives the document in the search appliance cache, but does not follow links on the Web page to other documents_").

Your suggestion of a config switch makes sense. What about having something like `robots.noFollow.strict` with a boolean value, where the outlinks would be filtered out completely when the mode is set to strict and left otherwise?

BTW you could always handle the outlinks in anyway you want if you extracted them from the DOM in a bespoke ParseFilter.
