### ISSUE TITLE
[External][Solr] The Solr storage should use 'autoSoftCommit' and 'autoCommit'

### ISSUE THREAD

**Issue by ludovic-boutros** [DigitalPebble/storm-crawler#177]
Currently the Solr storage modules send hard commits to Solr. 

I think this is not the good way to proceed.
These commits cause too much pressure on Solr. See the following screenshot.

![capture d ecran 2015-08-12 a 10 10 18](https://cloud.githubusercontent.com/assets/13764888/9488752/5a1f5b62-4bdc-11e5-82c4-ca2e59235618.png)

Instead, these modules should let Solr commit the documents with 'autoCommit' and 'autoSoftCommit' sections in the 'solrconfig' file.

**Comment by jorgelbg** [comment]
I think the more generic approach could be make this an option in the configuration file? In some cases I've seen than relying only on autoCommit or autoSoftCommit can be "problematic" that's why the module issue a hard commit every now and then. What do you think?

**Comment by ludovic-boutros** [comment]
Hi @jorgelbg,

I think that the usage of Solr in SC can be considered as a NRT use case.
In this type of use cases, I think explicit hard commits are not a good solution.

I really don't like having explicit commits in my code ;)

I've never had any bad experiences with autocommits, could you elaborate a bit please ? 

Another solution could be to remove explicit hard commits and add a _commitWithin_ parameter to each _add_ command ?

This would be an additional parameter. That would work too I think.

**Comment by jnioche** [comment]
@ludovic-boutros did you get an improvement to the perfs of the status updater by using soft commits? 

I expected the commit strategy (auto|soft|hard) to be done entirely on the SOLR config side and not at all in the code. Is that required because the client buffers the docs to index? Isn't there another SOLR client implementation which has a max doc / max time parameter? 

The current implementation would be problematic when a few docs are processed e.g. end of a crawl as we would not get the minimal size before we commit. See [https://github.com/DigitalPebble/storm-crawler/blob/master/external/aws/src/main/java/com/digitalpebble/stormcrawler/aws/bolt/CloudSearchConstants.java#L27] for how I handled that for CloudSearch.

@jorgelbg the handling of errors is incorrect. At the moment you just log the error which means that the input tuple gets acked. It would need to be failed either explicitely or by rethrowing the exception so that AbstractStatusUpdaterBolt can deal with it.

**Comment by ludovic-boutros** [comment]
@jnioche I've tested with _commitWithin_ and it works quite well. 
But I would prefer a strategy in the solrconfig file too.

I'm currently implementing this strategy: 
- no explicit commit in the code
- autocommit, autosoftcommit in the solr config file

and I think I will test with a standard SolrHttpClient which will send synchronously the documents. 
This way, it will be far easier to handle errors correctly.

Is it ok for you @jorgelbg and @jnioche ?

**Comment by jnioche** [comment]
Sounds good. Thanks

**Comment by jorgelbg** [comment]
@ludovic-boutros  In a separated project I've worked some time ago we had some troubles with the memory usage on the autocommit/autosoftcommit issue, this features works on a time/number of docs approach, since the length of the documents we were storing in Solr was changing a lot we faced some problems when configuring a low autocommit/autosoftcommint value caused the server to spent a lot of time writing to disk, a high value caused some OOM exceptions and server to crash; right now we use a combination of both, we have a relative long time for an autocommit configured in the solrconfig.xml and we issue some hard commits when indexing, kind of having an hybrid approach, which is what I've tried to mimmic here. 

@jnioche Actually the ConcurrentUpdateSolrClient queue the documents/requests which maximize the throughput of the IndexerBolt, I'm not aware on any SolrClient with docs/max time parameter (ES does a better job here on the client side), although this can be accomplished by configuration in the solrconfig.xml, file. The CUSC client does have a max queue size parameter which I exposed in the storm crawler configuration. 

if your only strategy is is based on hard commits then yes the document will be added/sent to Solr but not committed until the batch size is reached, but leveraging this with the autocommit/autosoftcommit the results will be available for search and will be committed eventually. 

If any error happens when the add/commit is issued against Solr the tuple is failed https://github.com/DigitalPebble/storm-crawler/blob/master/external/solr/src/main/java/com/digitalpebble/storm/crawler/solr/bolt/IndexerBolt.java#L144. The particular implementation of ConcurrentUpdateSolrClient will fail the entire batch and not report back which particular document failed is this what you meant? 

I don't have any trouble with getting this responsibility out of SC, in this case will handle all of this in the Solr side. 

@ludovic-boutros I would love to hear back from the SolrHttpClient test, we switched to CUSC mainly to increase the throughput of our indexer (the other project).

**Comment by jnioche** [comment]
@jorgelbg re-error handling \:I am talking about the StatusUpdater, not the indexing bolt. 

I was thinking about CUSC but had not realised it was returned by `connection.getClient()`; for some reason I thought we could also specify a max time but that's probably me confusing with ES.

**Comment by jorgelbg** [comment]
@jnioche Yes, ES does support this scenario, but not any Solr client I'm afraid.

About the error, you're right, sorry my bad! in the StatusUpdater the Exception is just logged, in this case I can throw a new `RuntimeException()` that will be caught by the `AbstractStatusUpdaterBolt`. The other way is not logging the exception at all at let it get caught directly by the `AbstractStatusUpdaterBolt`. The first is implemented in https://github.com/jorgelbg/storm-crawler/tree/solr-statusupdater-error. But since we're leaving the commit logic outside of storm crawler, then I should remove the commits on the entire solr module right?

**Comment by ludovic-boutros** [comment]
@jorgelbg Hopefully I will be ready tomorrow for a PR. I will let you know if we need to create batches with something like a callback mechanism in order to acknowledge tuples correctly.

**Comment by jnioche** [comment]
> But since we're leaving the commit logic outside of storm crawler, then I should remove the commits on the entire solr module right?

yes, we should have the same behaviour for both the StatusUpdater and the IndexingBolt.

**Comment by jorgelbg** [comment]
Ok, I'll wait until @ludovic-boutros wraps things up and then we can review the PR, if thats ok. The module README file also needs to be updated to remove the `solr.TYPE.commit.size` configuration option, but thats easy :)

**Comment by ludovic-boutros** [comment]
Ok, here is what I can observe now with a _HttpSolrClient_, auto commit and auto soft commit:

![capture d ecran 2015-08-27 a 16 30 54](https://cloud.githubusercontent.com/assets/13764888/9523366/f02bcdf4-4cd9-11e5-906e-f860b9a6fc4e.png)

It could require some tuning depending on the hardware/sharding.

I think we should not use the _ConcurrentUpdateSolrServer_ class because the updates are asynchronous and this means that the behavior would be different in a sharded environment (the _CouldSolrClient_ is synchronous).

The PR will follow today or tomorrow. It simplifies the code, which is always good.

**Comment by jnioche** [comment]
thanks @ludovic-boutros sounds great!

**Comment by ludovic-boutros** [comment]
PR done.
Comments welcome ;)

**Comment by jnioche** [comment]
@jorgelbg did you have a look at this?
