### ISSUE TITLE
Add bufferization in the Solr indexing process

### ISSUE THREAD

**Issue by ludovic-boutros** [DigitalPebble/storm-crawler#183]
Currently, each document to be indexed is directly sent to Solr.
This allows a very easy acknowledgement mechanism of Storm tuples.

In order to improve the throughput, a bufferization mechanism could be implemented.

This mechanism should take in account:
- non-cloud and cloud modes.
- correct errors management and tuple acknowlegement.

**Comment by jorgelbg** [comment]
I think we can extend the CUSC class, essentially this class does all the queuing for us, provides the threads to empty the queue as quickly as possible and provides a `handleError()` method that can be used to implement our own logic, by default this method only logs the error.

By default the CUSC client queue requests, meaning that if we keep 1 doc per request in the queue we can handle the case for one document failing to be indexed and then fail the tuple, this means that the acknowledge/failed action will be taken by the client instead of the bolt. The problem with Solr is that when a add request is made with several documents inside the batch fails and not report the actual doc that caused the error, but in the end will continue to send one doc per request if we want to ack/fail the actual document/tuple, the problem is we still get to send one doc per request.

**Comment by ludovic-boutros** [comment]
So true. I think it does not worth it.

And it is not recommended to use CUSC with SolrCloud.
The improvements are on the Solr side I think.

**Comment by jnioche** [comment]
Note to self \: http://lucene.apache.org/solr/6_4_1/solr-solrj/index.html?org/apache/solr/client/solrj/impl/ConcurrentUpdateSolrClient.html
