### ISSUE TITLE
Remove PrinterBolt and IndexerBolt.java

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#187]
[PrinterBolt](https://github.com/DigitalPebble/storm-crawler/blob/master/core/src/main/java/com/digitalpebble/storm/crawler/bolt/PrinterBolt.java) is not as useful as [StdOutIndexer](https://github.com/DigitalPebble/storm-crawler/blob/master/core/src/main/java/com/digitalpebble/storm/crawler/indexing/StdOutIndexer.java), which extends AbstractIndexerBolt and provides a similar functionality.

As for [IndexerBolt.jav](https://github.com/DigitalPebble/storm-crawler/blob/master/core/src/main/java/com/digitalpebble/storm/crawler/bolt/IndexerBolt.java), I doubt anyone ever uses it. All it does is add a level of abstraction over the actual implementation used. In practice it is just as quick to declare the right class in the topology directly compared to having to do that via configuration.

@DigitalPebble/committers-crawler any thoughts on this?

**Comment by jorgelbg** [comment]
:+1: on removing PrinterBolt, perhaps for testing purposes to do some sort of debugging could be helpful but this is very easy to implement if anyone need it.

 I agree that defining the configuration key is as easy as defining the right class in the topology, I would say even more logical, because you need to implement the topology class according to your needs and later on specify the FQDN in the configuration file, so :+1:, the only case I see for keeping IndexerBolt around is for quickly switching the indexer implementation, but how often this could be used?

**Comment by jnioche** [comment]
> perhaps for testing purposes to do some sort of debugging could be helpful 

we have StdOutIndexer exactly for that purpose

> how often this could be used

close to never I'd think

It probably creates more confusion than anything else

thanks for your comments

**Comment by jnioche** [comment]
We could add a simple bolt extending AbstractStatusUpdaterBolt, comparable to what StdOutIndexer does for the indexing. It would display the nextFetch Date for instance and would be useful for debugging. We can then remove the PrinterBolt

**Comment by jorgelbg** [comment]
What I meant with the debug purposes was basically to take a peek into the data sent between bolts, the StdOutIndexer does a great job for debugging what gets indexed/persisted in your storage. 

The alternative provided with a simple extending AbstractStatusUpdaterBolt looks like a great solution, although again since the PrinterBolt is so easy to implement perhaps the debugging thinking I was using is not required at all, but guess that providing the new bolt doesn't do any harm.

**Comment by jnioche** [comment]
@jorgelbg see [https://issues.apache.org/jira/browse/STORM-954] in the upcoming 0.11.0. This would be a nicer way of having a generic debugger than the PrinterBolt

**Comment by jnioche** [comment]
Implemented in [56e19ea7b60389bb2acd07b59caa32dd28a31290]
