### ISSUE TITLE
Reduce metrics chatter

### ISSUE THREAD

**Issue by mattburns** [DigitalPebble/storm-crawler#246]
When writing metrics to Elasticsearch, the index can get big enough to affect performance of Elasticsearch. Here are my thoughts on things that may help reduce the burden on Elasticsearch:

1. Log fewer stats
  1. Configurable (crawler-conf) whitelist/blacklist of metric names?
  1. Maybe just skip writing of internal ones (starting with "__") used by storm-ui.
1. Log less frequently
  1. Configurable granularity of update frequency (time bucket size currently hardcoded to 10 seconds)
1. Regularly prune the DB
  1. Have two indexes (metrics-fine and metrics-coarse?) one with high resolution (update frequency) but short TTL*, and the other the opposite.
  1. Have a silly utility class that can prune the metrics index using a . eg, "delete metrics older than X" or "delete metrics with name Y"
  1. Use the new [delete by query plugin](https://www.elastic.co/guide/en/elasticsearch/plugins/2.2/plugins-delete-by-query.html)?

*Note, [elastic have deprecated _ttl](https://www.elastic.co/guide/en/elasticsearch/reference/2.2/mapping-ttl-field.html), we should probably move to index-per-timeframe?

What are your thoughts to those suggestions? I'd prefer logging less over pruning because it also reduces the network chatter etc. I'm tempted by the whitelist/blacklist idea because it seems pretty straight forward. I was thinking you could specify something like this in the crawler-conf:

```
metrics.whitelist:
- fetcher_counter.fetched
- fetcher_counter.exception
```

Thoughts?

**Comment by jnioche** [comment]
Black/whitelist would be a good initial approach, followed by configurable per component update frequency.
I am less keen on the regular pruning of the DB too. Having 2 indices fine vs coarse would be tricky as for pruning this is pretty much what _ttl does. Since we are on ES 1.x for now we can just use it. Later on we could indeed look at index-per-timeframe.

I expect that the more bolt instances (e.g. SimpleFetcher) in a topology, the more acute the problem becomes.

The metrics index could be handled by a separate ES machine to avoid degrading the perf of the one used for the status and/or index.

As a side note, the metrics part of the ES plugin is not specific to StormCrawler so I was wondering whether to contribute it to Storm [https://github.com/apache/storm/tree/master/external/storm-elasticsearch/src/main/java/org/apache/storm/elasticsearch] or release it separately. I would maybe base it on Jest (see #221) so that users could index to the AWS Elasticsearch service which does not support the native API. Do you have any thoughts on this?

**Comment by mattburns** [comment]
Agreed.
Your thoughts about the SimpleFetcherBolt highlight a good point. For instance, I've configured my `fetcher_counter.fetched` metric to bucket into 30 second intervals. If there was one bolt, I would have 20 metrics written in a 10 minute period. However, I have 200 fetcher tasks and therefore I get ~4000. I can't just multiply the interval by the number of fetchers because they all stay in sync. You can see from this graph how my 200 tasks all attempt to write their metrics at the same time every 30 seconds:

![image](https://cloud.githubusercontent.com/assets/1316126/12783560/36bd74b6-ca7a-11e5-9f8c-d0644722d446.png)

I have no strong feelings either way about where the ES plugin belongs :)

**Comment by jnioche** [comment]
@mattburns what about being able to configure the metrics frequency per component? Would this still be useful and if so should we reopen this issue?

**Comment by mattburns** [comment]
Yeah, that would be very useful. The following code is in the SimpleFetcherBolt:

```
this.eventCounter = context.registerMetric("fetcher_counter", new MultiCountMetric(), 10);
```

The `10` be configurable, but there should be also be a way for eventCounter to be shared across all bolts of this type rather than each bolt constructing its own?

**Comment by jnioche** [comment]
The counter could be shared by being a static field however this would not be across all bots, just the ones that live in the same JVM. Moreover I think it makes sense to be able to get the stats per instance.

Will make the change for configuring the time for the SimpleFetcherBolt only as it is likely to be the component we use the most instances of.

**Comment by mattburns** [comment]
Ok, cool, per JVM would be fine :)

**Comment by jnioche** [comment]
We can now configure how often the metrics will be generated for both flavours of FetcherBolts. 
`fetcher.metrics.time.bucket.secs: 10`

@mattburns - nope. I'd rather keep the info per instance ;-)
