### ISSUE TITLE
ES: use SHA256 as doc_id

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#385]
instead of the document's URL. The URL is stored as a separate field anyway. Would there be a gain in performance? There would certainly be a gain in size as all the URLs no matter how large or small would all be represented in 64 chars.

**Comment by sebastian-nagel** [comment]
Good idea. The ES document API is not easy to use with URLs as IDs because of the configurable routing (by host/domain/ip) and because reserved characters (`/?+&`) have to be escaped.
- a [URL-safe base64 encoding](https://en.wikipedia.org/wiki/Base64#URL_applications) similar to [ES autogenerated IDs](https://www.elastic.co/guide/en/elasticsearch/guide/current/index-doc.html#_autogenerating_ids) would shorten id strings by 30%
- could also think about a compound id as in [Ahad's crawler](/commoncrawl/commoncrawl-crawler/blob/master/src/org/commoncrawl/protocol/protocol.jr) (see [slides](http://www.slideshare.net/hadoopusergroup/building-a-scalable-web-crawler-with-hadoop?qid=fc300654-aa09-49d9-8292-52922f98716e&v=qf1&b=&from_search=6) page 10)
