### ISSUE TITLE
Sitemap file not detected

### ISSUE THREAD

**Issue by kanwarkakkar** [DigitalPebble/storm-crawler#409]
I am trying to crawl sitemap with extension .xml.  e.g https://keywordcountry.com/sitemap.xml but it is not parsing the sitemap. After debugging I found out in [SiteMapParserBolt.java ](https://github.com/DigitalPebble/storm-crawler/blob/b1d942ed1f1e8807baa5c46d0fa159e03693c28c/core/src/main/java/com/digitalpebble/stormcrawler/bolt/SiteMapParserBolt.java) at line number 104  **Bytes.indexOf(beginning, clue)**  is returning **-1** and not processing it further. In JSoupParserBolt.java it is giving exception of content type application/xml

**Comment by jnioche** [comment]
hi @kanwarkakkar 

The explanation for this is that the the SitemapParserBolt can't guess that the file is a sitemap because the clue it uses (_http://www.sitemaps.org/schemas/sitemap/0.9_) is located beyond the 200 chars limit. We could change this to a higher value and/or make it configurable or add different clues e.g. if file is named sitemap.xml.

The exception is JSoupParserBolt is expected.

There are already a number of things you can do to fix the problem. First, make sure `isSitemap` is listed in `metadata.persist`

1. if your seed file lists this particular URL then you can add the key value _isSitemap=true_ separated from the URL by a tab
2. if not, set 'sitemapsAutoDiscovery: true' in the config, this will persist _isSitemap=true_ and discover any sitemaps from the robots.txt

I'll add an additional clue to the detection and make the char limit greater and configurable.

Thanks

**Comment by jnioche** [comment]
@kanwarkakkar I made the offset configurable. Decided not to add the clue based on the filename in the end.
