### ISSUE TITLE
Increase detect.charset.maxlength default value

### ISSUE THREAD

**Issue by hatemalimam** [DigitalPebble/storm-crawler#537]
I had a case where the main seed was goal.com/ar, it's an arabic website with a charset of `UTF-8`, after some debugging I found out that the class responsible for detecting the charset is [CharsetIdentification](https://github.com/DigitalPebble/storm-crawler/blob/master/core/src/main/java/com/digitalpebble/stormcrawler/util/CharsetIdentification.java), the detected charset  for that seed was wrong, it has to be `UTF-8`, instead the returned value is `ISO-8859-1`.

Basically the server is not providing a `content-type` header (`httpCharset`) nor the `htmlCharset` is being retrieved (due the shortness of the default `detect.charset.maxlength` value) , so that `hintCharset` is always `null`.

What I found out in many cases (not only in that particular seed), regarding RTL websites that `2048` of a maxlength is too few,
in my case increasing that to `10000` for example fixed the issue.

Here's an example:
URL:
http://www.goal.com/ar/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1/1

Expected result:
أخبار كرة القدم، صفحة 1 من 780 | Goal.com

Actual result with 2048 of a maxlength:
Ø£Ø®Ø¨Ø§Ø± ÙØ±Ø© Ø§ÙÙØ¯ÙØ ØµÙØ­Ø© 1 ÙÙ 780 \| Goal.com

Any particular reason why the default value is `2048` ?

https://github.com/DigitalPebble/storm-crawler/blob/2493ae73292f7d7883eb1c45a7533d808630f030/core/src/main/resources/crawler-default.yaml#L99

**Comment by jnioche** [comment]
See #391 for why we needed to limit it. As pointed out in [#438](https://github.com/DigitalPebble/storm-crawler/issues/438#issuecomment-287636762), 2048 could indeed be too low.
Maybe the [inputFilter](https://github.com/DigitalPebble/storm-crawler/blob/master/core/src/main/java/com/digitalpebble/stormcrawler/util/CharsetIdentification.java#L111) lets scripts through which influences the detection. Maybe this could be improved as well. 

We could also add a configuration so that the value set in the HTML is used if it is valid and there is nothing from the HTTP headers and the value is valid. 

Of course we could simply go for a larger value like the one you suggested. Do you want to open a PR for this? Thanks

**Comment by kkrugler** [comment]
Actually I see two or three potential separate issues here...

1. http://goal.com/ar returns a 301 (permanent redirect), and the response headers have `Content-Type: text/html; charset=iso-8859-1`. I assume that this charset info is ignored, but seems curious that it matches the incorrect charset being reported.
1. http://www.goal.com/ar (the redirect) returns in the http response headers `Content-Type: text/html; charset=UTF-8`. So I would assume that should be used, unless the HTML has something that overrides it.
1. The reason the `<meta charset="utf-8" />` HTML element isn't found in the first 2K of text is because there's a large `<script>` element right before it. This illustrates the fundamental issue around trying to read an arbitrary amount of text to find HTML elements; you can always insert enough other text to push what you're looking for out of the buffer. I think the only viable solution is to add a "smart" HTML element processor, which incrementally reads until it hits the `</head>` tag (or some other element that can never appear in the head block, or some really big limit).

**Comment by hatemalimam** [comment]
@kkrugler Interesting.
Apart from the fact that a "smart" HTML processor is indeed a nice idea, but for time-being increasing that 2K seems to me a necessity.

@jnioche 

> We could also add a configuration so that the value set in the HTML is used if it is valid and there is nothing from the HTTP headers and the value is valid.

You mean like skipping the guessing part, right before [`hintCharset`](https://github.com/DigitalPebble/storm-crawler/blob/e394917f65e22b8e4512279cee603e75cdb2ca31/core/src/main/java/com/digitalpebble/stormcrawler/util/CharsetIdentification.java#L59) ?
we could define a new config, for example:  `detect.force.html.charset`

In that case we skip the [`getCharsetFromText`](https://github.com/DigitalPebble/storm-crawler/blob/e394917f65e22b8e4512279cee603e75cdb2ca31/core/src/main/java/com/digitalpebble/stormcrawler/util/CharsetIdentification.java#L67) part and return `htmlCharset` if that is set to `true` ?

Could be an idea.

**Comment by hatemalimam** [comment]
For now I'll open a PR to increase the default value to 10K.

**Comment by kkrugler** [comment]
@hatemalimam - the main issue with increasing the size to 10K is that you'll still hit badly-formatted HTML that has the meta element after 10K of text.

One interesting reference - see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta for their notes on charset detection. They state that the `<meta>` element must come within the first 1K of text. And that the `Content-Type` header and any BOM overrides what's in the `<meta>` element.

**Comment by jnioche** [comment]
Closing this one for now, we can continue the discussion on the best approach to use in a separate issue or better at crawler-commons https://github.com/crawler-commons/crawler-commons/issues/171
