### ISSUE TITLE
Investigate use of async IO for Fetcher

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#54]
The fetcher bolts currently block IO. Doing asynchronous IO would certainly provide better throughput. 

[https://jfarcand.wordpress.com/2010/12/21/going-asynchronous-using-asynchttpclient-the-basic/] provides interesting examples

**Comment by kkrugler** [comment]
One data point - Oleg Kalnichevski (main author of HttpClient) has repeatedly said that he thinks sync outperforms async, e.g. "From my personal experience a decent blocking HTTP client can be
expected to outperform a decent non-blocking HTTP client by 50 to 100%".

At very massive parallelism using async would definitely make sense, though I've run HttpClient with 2000+ threads on one box with appropriate tuning of thread stack size, etc.

But I also enjoy the asynhttpclient API, and have used it in various projects, so I'm not suggesting that it shouldn't be used. I'm just saying that the most knowledgeable person I know about HTTP comms says it won't be a performance win.

**Comment by eshioji** [comment]
Oh sorry I meant to be working on this but got bogged down with lots of things happening in my former company.. Feeling rather guilty... It's much more relaxed now, I could work on this if you want.

As for performance, I think there is definitely a good chance we can score a gain. In the world of web servers, it's been established that non-blocking is advantageous because you interact with clients that are low-performing, resulting in lots of wait time on your end, which you can then reduce by talking to lots of clients at the same time. This seems similar to what we'd have in a crawling situation.

I still have the code for this, so would be easy enough to add.

**Comment by jnioche** [comment]
@kkrugler thanks for your comments, very useful as usual.
@eshioji great to hear from you. feel free to create a separate branch to play with. I expect you'd need to modify the protocol interface and/or the Fetcher logic quite a bit

**Comment by jakekdodd** [comment]
Each task of the SimpleFetcherBolt will block IO to make its HTTP request. When using that bolt, concurrency can be achieved by tuning the number of executors (threads) and tasks.

The regular FetcherBolt is already asynchronous from the perspective of Storm, and its concurrency is limited by the number of threads in the pool. The size of the thread pool is functionally equivalent to the max connections in AsyncHTTPClient's connection pool.

So, my best guess is that moving to an async HTTP client library will give us better memory performance, but not necessarily better throughput. My hypothesis is that you'll achieve bandwidth saturation before running out of memory because of too many component executors (in the case of SimpleFetcherBolt) or too many pool threads (in the case of FetcherBolt).

**Comment by eshioji** [comment]
Created a feature branch: https://github.com/DigitalPebble/storm-crawler/tree/feature/non-blocking-fetcher

I haven't done the fetcher bit yet, but it does illustrate the proposed refactoring on the protocol/robot rule parser interface. Note that I used the Guava classes copied into Storm's source. This will avoid having a dependency to Guava but will tie the code to Storm. Am not sure if this is the right thing to do.

**Comment by jakekdodd** [comment]
> This will avoid having a dependency to Guava but will tie the code to Storm. Am not sure if this is the right thing to do.

We already switched over to the storm-packaged Guava classes in other locations in the codebase, so I think that's the right approach

**Comment by jnioche** [comment]
I'll have a closer look at this when I get a moment. Quick comment for now : I had a http protocol implementation based on AsyncHttpClient but as it uses Netty as a default provider, this caused all sorts of issues with Storm itself. Probably not a problem anymore now that Storm shaded Netty but worth keeping in mind. See [https://storm.apache.org/2014/11/25/storm093-released.html#reduced-dependency-conflicts]

**Comment by eshioji** [comment]
@jakekdodd Ah I see, thank you!
@jnioche That would be great. Re: dependency clash I didn't have to add Ning's AsyncHttpClient as one of the dependencies apparently already had it. It also seemed to run OK when I did a smoke test. Hopefully it will be fine..

**Comment by eshioji** [comment]
@jnioche Did a first pass of the NonBlockingFetcherBolt. It's nowhere complete but it does fetch URLs ok. Would maybe fit for a performance test with a bit more work.

**Comment by jnioche** [comment]
@eshioji I never got to investigate this in more details. The codebase has since evolved an awful lot. From your earlier comments you mentioned that there wouldn't be much gain in using async, is that still what you think? If so shall we close this issue?

**Comment by jnioche** [comment]
Closing as there seems to be little interest in this.
