### ISSUE TITLE
various dependency upgrades

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#808]
`mvn versions:display-dependency-updates | grep "\->" | sort | uniq`

[INFO]   com.amazonaws:aws-java-sdk-cloudsearch ........... 1.10.77 -> 1.11.812
[INFO]   com.amazonaws:aws-java-sdk-s3 .................... 1.10.77 -> 1.11.812
[INFO]   com.fasterxml.jackson.core:jackson-databind ....... 2.9.10.5 -> 2.11.1
[INFO]   com.github.tomakehurst:wiremock ..................... 2.19.0 -> 2.26.3
[INFO]   com.github.tomakehurst:wiremock ..................... 2.22.0 -> 2.26.3
[INFO]   com.google.guava:guava .......................... 27.1-jre -> 29.0-jre
[INFO]   com.ibm.icu:icu4j ....................................... 64.1 -> 67.1
[INFO]   com.rometools:rome .................................. 1.12.0 -> 1.14.1
[INFO]   com.squareup.okhttp3:okhttp .......................... 3.14.2 -> 4.7.2
[INFO]   junit:junit ............................................. 4.11 -> 4.13
[INFO]   org.apache.httpcomponents:httpclient ................. 4.5.8 -> 4.5.12
[INFO]   org.apache.solr:solr-solrj ............................ 7.5.0 -> 8.5.1
[INFO]   org.jsoup:jsoup ..................................... 1.12.1 -> 1.13.1
[INFO]   org.mockito:mockito-all ......................... 1.10.8 -> 2.0.2-beta
[INFO]   org.seleniumhq.selenium:selenium-support ...... 3.4.0 -> 4.0.0-alpha-6
[INFO]   org.yaml:snakeyaml ...................................... 1.24 -> 1.26

**Comment by matiascrespof** [comment]
Hello @jnioche, about dependency **com.squareup.okhttp3:okhttp** , for version 3.14.2, we noticed after some time certain urls getting stuck in Fetcher Bolt (configuring debugfiletrigger file in our project, we noticed urls from certain domains never fetched) 
We downgraded dependency to previous version of crawler 1.13 in our pom file (okhttp dependency 3.11.0) and issue was gone, same result upgrading to 4.7.2, same described in this task.

We didn't investigate in detail the cause since the issue is gone and everything seems to work ok, we just wanted to give you a heads up that for crawler version 1.16 there is a potential issue with that library.

**Comment by jnioche** [comment]
thanks @matiascrespof, this is very useful. If these URLs get stuck then they certainly time out and get failed in the spout, in which case it should be easy to find out what they are. I might upgrade to 4.7.2 and see if I can reproduce the problem. Thanks again

**Comment by jnioche** [comment]
note to self mockito 2 has been in beta for 5 years, probably best to stick to the latest 1 version -> 1.10.19

**Comment by matiascrespof** [comment]
> thanks @matiascrespof, this is very useful. If these URLs get stuck then they certainly time out and get failed in the spout, in which case it should be easy to find out what they are. I might upgrade to 4.7.2 and see if I can reproduce the problem. Thanks again

Sorry, I meant when we upgraded to 4.7.2, the issue is gone, we only experimented the issue with 3.14.2.

True, the urls get failed in the spout but still the queue (FetchItemQueue) doesn't clean up the url, since we think the thread gets stuck when perform call to protocol (method getProtocolOutput,  OkHttpClient client, from com.digitalpebble.stormcrawler.protocol.okhttp.HttpProtocol )

We were not able to reproduce it locally, since it happens when crawler is running  after a while..

I hope it helps @jnioche !
Thanks

**Comment by jnioche** [comment]
ok, thanks @matiascrespof, will definitely update to 4.7.2 then.

**Comment by jnioche** [comment]
the solr upgrade is already covered in #701
