### ISSUE TITLE
HybridSpout PartitionField can only be field used in URLPartitioner

### ISSUE THREAD

**Issue by GerbenKD** [DigitalPebble/storm-crawler#887]
The parameter `partitionField` in the `HybridSpout` can only be the same field as the one used in the `URLPartitioner`.

The `emptyQueue()` method in the `HybridSpout` filters on the `queueName` machting the `partitionField`:
https://github.com/DigitalPebble/storm-crawler/blob/3af65c5950fbfcb46aff05e57d56e29e38e00299/external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/HybridSpout.java#L107

However, the `queuename` is created in `AbstractURLBuffer` with the key from the `URLPartitioner`. So, the `partitionField` cannot be anything else than the `URLPartitioner` allows.

**Comment by jnioche** [comment]
We could modify AggregationSpout so that it uses the value found in the field corresponding to _partitionField_  and use that to send to the URLBuffer; so that would be a guarantee that the value are definitely the same.

However in practice, URLPartitioner should be configured in the same way for the StatusUpdaterBolt and the spouts, so the values within_partitionField_ should be the same, shouldn't they?

**Comment by jnioche** [comment]
@GerbenKD could it be an issue due to the fact that you are not using the standard StatusUpdaterBolt and hence don't use URLPartitioner to generate the values that are used for partitioning?

**Comment by GerbenKD** [comment]
Hi Julien. Yes, you are right, that is exactly the issue. Sorry for the confusion.
It seems that I was confused as to what the setting `es.status.bucket.field` does. It tells where to store the key, not which field to use as a key. And this fieldname can be anything that isn't used. Closing the issue. 

Thanks,

Gerben
