### ISSUE TITLE
http.content.limit has effect on robots.txt

### ISSUE THREAD

**Issue by wowasa** [DigitalPebble/storm-crawler#921]
Since we need only some header information in our project we set »http.content.limit: 0« and we just realized that this setting concerns also the robots.txt, so that f.e. a crawl-delay set there isn't respected anymore. 

If it's not a bug, it might be reasonable to point out the effect of the setting on the processing of robots.txt

**Comment by sebastian-nagel** [comment]
Thanks, good point. It'd consider it as a bug because the [robots.txt RFC draft](https://datatracker.ietf.org/doc/html/draft-rep-wg-topic-00#section-2.5) specifies that at least 500 kiB are fetched.

Sending a HEAD request (#485) might work around the problem ([only implemented in httpclient](https://github.com/DigitalPebble/storm-crawler/wiki/Protocols#feature-grid)).

**Comment by wowasa** [comment]
thank you, Sebastian: our link checking application is sending a head request anyway in the first attempt, since we just need some header info. Only in case of non-ok status response it's sending a get request in a second attempt. But since we're checking millions of links without any need for content I would prefer »http.content.limit: 0«. 
Hence I would fix the issue with an own instance of CloseableHttpClient with default settings to read the robots.txt. Or do you have a different approach?

**Comment by sebastian-nagel** [comment]
I'd suggest to pass a page-specific "http.content.limit" from HttpRobotRulesParser to the protocol via metadata. I'll open a PR. The fix should be independent of the used protocol implementation (okhttp, httpclient) and it should still use all other protocol features (proxy, connection pool, etc.)
